# Generated by Django 5.2 on 2025-05-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapreset',
            name='last_updated_by',
        ),
    ]
