# Generated by Django 5.2 on 2025-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprep', '0004_datasource_datapreset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
